// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lab1_z1_lab1_z1,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-csg325-1Q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.241500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=60,HLS_VERSION=2021_2}" *)

module lab1_z1 (
        ap_local_block,
        ap_local_deadlock,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        c,
        d,
        ap_return
);


output   ap_local_block;
output   ap_local_deadlock;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] a;
input  [15:0] b;
input  [15:0] c;
input  [15:0] d;
output  [31:0] ap_return;

wire  signed [16:0] sext_ln5_fu_48_p1;
wire  signed [16:0] sext_ln5_2_fu_56_p1;
wire   [16:0] add_ln5_fu_64_p2;
wire  signed [17:0] sext_ln5_4_fu_70_p1;
wire  signed [17:0] sext_ln5_1_fu_52_p1;
wire   [17:0] add_ln5_1_fu_74_p2;
wire  signed [17:0] sext_ln5_3_fu_60_p1;
wire   [17:0] y_fu_80_p2;
wire    ap_ce_reg;

assign add_ln5_1_fu_74_p2 = ($signed(sext_ln5_4_fu_70_p1) + $signed(sext_ln5_1_fu_52_p1));

assign add_ln5_fu_64_p2 = ($signed(sext_ln5_fu_48_p1) + $signed(sext_ln5_2_fu_56_p1));

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign ap_ready = ap_start;

assign ap_return = $signed(y_fu_80_p2);

assign sext_ln5_1_fu_52_p1 = $signed(b);

assign sext_ln5_2_fu_56_p1 = $signed(c);

assign sext_ln5_3_fu_60_p1 = $signed(d);

assign sext_ln5_4_fu_70_p1 = $signed(add_ln5_fu_64_p2);

assign sext_ln5_fu_48_p1 = $signed(a);

assign y_fu_80_p2 = ($signed(add_ln5_1_fu_74_p2) - $signed(sext_ln5_3_fu_60_p1));

endmodule //lab1_z1
