// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="foo_m_foo_m,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-csg325-1Q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.470000,HLS_SYN_LAT=65541,HLS_SYN_TPT=65538,HLS_SYN_MEM=96,HLS_SYN_DSP=0,HLS_SYN_FF=760,HLS_SYN_LUT=711,HLS_VERSION=2021_2}" *)

module foo_m (
        ap_local_block,
        ap_local_deadlock,
        data_in_address0,
        data_in_ce0,
        data_in_d0,
        data_in_q0,
        data_in_we0,
        data_in_address1,
        data_in_ce1,
        data_in_d1,
        data_in_q1,
        data_in_we1,
        scale,
        data_out1_address0,
        data_out1_ce0,
        data_out1_d0,
        data_out1_q0,
        data_out1_we0,
        data_out1_address1,
        data_out1_ce1,
        data_out1_d1,
        data_out1_q1,
        data_out1_we1,
        data_out2_address0,
        data_out2_ce0,
        data_out2_d0,
        data_out2_q0,
        data_out2_we0,
        data_out2_address1,
        data_out2_ce1,
        data_out2_d1,
        data_out2_q1,
        data_out2_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output   ap_local_block;
output   ap_local_deadlock;
output  [13:0] data_in_address0;
output   data_in_ce0;
output  [31:0] data_in_d0;
input  [31:0] data_in_q0;
output   data_in_we0;
output  [13:0] data_in_address1;
output   data_in_ce1;
output  [31:0] data_in_d1;
input  [31:0] data_in_q1;
output   data_in_we1;
input  [31:0] scale;
output  [13:0] data_out1_address0;
output   data_out1_ce0;
output  [31:0] data_out1_d0;
input  [31:0] data_out1_q0;
output   data_out1_we0;
output  [13:0] data_out1_address1;
output   data_out1_ce1;
output  [31:0] data_out1_d1;
input  [31:0] data_out1_q1;
output   data_out1_we1;
output  [13:0] data_out2_address0;
output   data_out2_ce0;
output  [31:0] data_out2_d0;
input  [31:0] data_out2_q0;
output   data_out2_we0;
output  [13:0] data_out2_address1;
output   data_out2_ce1;
output  [31:0] data_out2_d1;
input  [31:0] data_out2_q1;
output   data_out2_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Loop_Loop1_proc_U0_ap_start;
wire    Loop_Loop1_proc_U0_ap_done;
wire    Loop_Loop1_proc_U0_ap_continue;
wire    Loop_Loop1_proc_U0_ap_idle;
wire    Loop_Loop1_proc_U0_ap_ready;
wire    Loop_Loop1_proc_U0_start_out;
wire    Loop_Loop1_proc_U0_start_write;
wire   [13:0] Loop_Loop1_proc_U0_data_in_address0;
wire    Loop_Loop1_proc_U0_data_in_ce0;
wire   [31:0] Loop_Loop1_proc_U0_temp1_din;
wire    Loop_Loop1_proc_U0_temp1_write;
wire    split_U0_ap_start;
wire    split_U0_start_full_n;
wire    split_U0_ap_done;
wire    split_U0_ap_continue;
wire    split_U0_ap_idle;
wire    split_U0_ap_ready;
wire    split_U0_start_out;
wire    split_U0_start_write;
wire    split_U0_in_r_read;
wire   [31:0] split_U0_out1_din;
wire    split_U0_out1_write;
wire   [31:0] split_U0_out2_din;
wire    split_U0_out2_write;
wire    Loop_Loop2_proc_U0_ap_start;
wire    Loop_Loop2_proc_U0_ap_done;
wire    Loop_Loop2_proc_U0_ap_continue;
wire    Loop_Loop2_proc_U0_ap_idle;
wire    Loop_Loop2_proc_U0_ap_ready;
wire    Loop_Loop2_proc_U0_temp2_read;
wire   [13:0] Loop_Loop2_proc_U0_data_out1_address0;
wire    Loop_Loop2_proc_U0_data_out1_ce0;
wire    Loop_Loop2_proc_U0_data_out1_we0;
wire   [31:0] Loop_Loop2_proc_U0_data_out1_d0;
wire    Loop_Loop3_proc_U0_ap_start;
wire    Loop_Loop3_proc_U0_ap_done;
wire    Loop_Loop3_proc_U0_ap_continue;
wire    Loop_Loop3_proc_U0_ap_idle;
wire    Loop_Loop3_proc_U0_ap_ready;
wire    Loop_Loop3_proc_U0_temp3_read;
wire   [13:0] Loop_Loop3_proc_U0_data_out2_address0;
wire    Loop_Loop3_proc_U0_data_out2_ce0;
wire    Loop_Loop3_proc_U0_data_out2_we0;
wire   [31:0] Loop_Loop3_proc_U0_data_out2_d0;
wire    temp1_full_n;
wire   [31:0] temp1_dout;
wire    temp1_empty_n;
wire    temp2_full_n;
wire   [31:0] temp2_dout;
wire    temp2_empty_n;
wire    temp3_full_n;
wire   [31:0] temp3_dout;
wire    temp3_empty_n;
wire    ap_sync_done;
wire   [0:0] start_for_split_U0_din;
wire    start_for_split_U0_full_n;
wire   [0:0] start_for_split_U0_dout;
wire    start_for_split_U0_empty_n;
wire   [0:0] start_for_Loop_Loop2_proc_U0_din;
wire    start_for_Loop_Loop2_proc_U0_full_n;
wire   [0:0] start_for_Loop_Loop2_proc_U0_dout;
wire    start_for_Loop_Loop2_proc_U0_empty_n;
wire   [0:0] start_for_Loop_Loop3_proc_U0_din;
wire    start_for_Loop_Loop3_proc_U0_full_n;
wire   [0:0] start_for_Loop_Loop3_proc_U0_dout;
wire    start_for_Loop_Loop3_proc_U0_empty_n;

foo_m_Loop_Loop1_proc Loop_Loop1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Loop1_proc_U0_ap_start),
    .start_full_n(start_for_split_U0_full_n),
    .ap_done(Loop_Loop1_proc_U0_ap_done),
    .ap_continue(Loop_Loop1_proc_U0_ap_continue),
    .ap_idle(Loop_Loop1_proc_U0_ap_idle),
    .ap_ready(Loop_Loop1_proc_U0_ap_ready),
    .start_out(Loop_Loop1_proc_U0_start_out),
    .start_write(Loop_Loop1_proc_U0_start_write),
    .data_in_address0(Loop_Loop1_proc_U0_data_in_address0),
    .data_in_ce0(Loop_Loop1_proc_U0_data_in_ce0),
    .data_in_q0(data_in_q0),
    .scale(scale),
    .temp1_din(Loop_Loop1_proc_U0_temp1_din),
    .temp1_full_n(temp1_full_n),
    .temp1_write(Loop_Loop1_proc_U0_temp1_write)
);

foo_m_split split_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(split_U0_ap_start),
    .start_full_n(split_U0_start_full_n),
    .ap_done(split_U0_ap_done),
    .ap_continue(split_U0_ap_continue),
    .ap_idle(split_U0_ap_idle),
    .ap_ready(split_U0_ap_ready),
    .start_out(split_U0_start_out),
    .start_write(split_U0_start_write),
    .in_r_dout(temp1_dout),
    .in_r_empty_n(temp1_empty_n),
    .in_r_read(split_U0_in_r_read),
    .out1_din(split_U0_out1_din),
    .out1_full_n(temp2_full_n),
    .out1_write(split_U0_out1_write),
    .out2_din(split_U0_out2_din),
    .out2_full_n(temp3_full_n),
    .out2_write(split_U0_out2_write)
);

foo_m_Loop_Loop2_proc Loop_Loop2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Loop2_proc_U0_ap_start),
    .ap_done(Loop_Loop2_proc_U0_ap_done),
    .ap_continue(Loop_Loop2_proc_U0_ap_continue),
    .ap_idle(Loop_Loop2_proc_U0_ap_idle),
    .ap_ready(Loop_Loop2_proc_U0_ap_ready),
    .temp2_dout(temp2_dout),
    .temp2_empty_n(temp2_empty_n),
    .temp2_read(Loop_Loop2_proc_U0_temp2_read),
    .data_out1_address0(Loop_Loop2_proc_U0_data_out1_address0),
    .data_out1_ce0(Loop_Loop2_proc_U0_data_out1_ce0),
    .data_out1_we0(Loop_Loop2_proc_U0_data_out1_we0),
    .data_out1_d0(Loop_Loop2_proc_U0_data_out1_d0)
);

foo_m_Loop_Loop3_proc Loop_Loop3_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Loop3_proc_U0_ap_start),
    .ap_done(Loop_Loop3_proc_U0_ap_done),
    .ap_continue(Loop_Loop3_proc_U0_ap_continue),
    .ap_idle(Loop_Loop3_proc_U0_ap_idle),
    .ap_ready(Loop_Loop3_proc_U0_ap_ready),
    .temp3_dout(temp3_dout),
    .temp3_empty_n(temp3_empty_n),
    .temp3_read(Loop_Loop3_proc_U0_temp3_read),
    .data_out2_address0(Loop_Loop3_proc_U0_data_out2_address0),
    .data_out2_ce0(Loop_Loop3_proc_U0_data_out2_ce0),
    .data_out2_we0(Loop_Loop3_proc_U0_data_out2_we0),
    .data_out2_d0(Loop_Loop3_proc_U0_data_out2_d0)
);

foo_m_fifo_w32_d16384_A temp1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_Loop1_proc_U0_temp1_din),
    .if_full_n(temp1_full_n),
    .if_write(Loop_Loop1_proc_U0_temp1_write),
    .if_dout(temp1_dout),
    .if_empty_n(temp1_empty_n),
    .if_read(split_U0_in_r_read)
);

foo_m_fifo_w32_d16384_A temp2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(split_U0_out1_din),
    .if_full_n(temp2_full_n),
    .if_write(split_U0_out1_write),
    .if_dout(temp2_dout),
    .if_empty_n(temp2_empty_n),
    .if_read(Loop_Loop2_proc_U0_temp2_read)
);

foo_m_fifo_w32_d16384_A temp3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(split_U0_out2_din),
    .if_full_n(temp3_full_n),
    .if_write(split_U0_out2_write),
    .if_dout(temp3_dout),
    .if_empty_n(temp3_empty_n),
    .if_read(Loop_Loop3_proc_U0_temp3_read)
);

foo_m_start_for_split_U0 start_for_split_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_split_U0_din),
    .if_full_n(start_for_split_U0_full_n),
    .if_write(Loop_Loop1_proc_U0_start_write),
    .if_dout(start_for_split_U0_dout),
    .if_empty_n(start_for_split_U0_empty_n),
    .if_read(split_U0_ap_ready)
);

foo_m_start_for_Loop_Loop2_proc_U0 start_for_Loop_Loop2_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_Loop2_proc_U0_din),
    .if_full_n(start_for_Loop_Loop2_proc_U0_full_n),
    .if_write(split_U0_start_write),
    .if_dout(start_for_Loop_Loop2_proc_U0_dout),
    .if_empty_n(start_for_Loop_Loop2_proc_U0_empty_n),
    .if_read(Loop_Loop2_proc_U0_ap_ready)
);

foo_m_start_for_Loop_Loop3_proc_U0 start_for_Loop_Loop3_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_Loop3_proc_U0_din),
    .if_full_n(start_for_Loop_Loop3_proc_U0_full_n),
    .if_write(split_U0_start_write),
    .if_dout(start_for_Loop_Loop3_proc_U0_dout),
    .if_empty_n(start_for_Loop_Loop3_proc_U0_empty_n),
    .if_read(Loop_Loop3_proc_U0_ap_ready)
);

assign Loop_Loop1_proc_U0_ap_continue = 1'b1;

assign Loop_Loop1_proc_U0_ap_start = ap_start;

assign Loop_Loop2_proc_U0_ap_continue = ap_sync_done;

assign Loop_Loop2_proc_U0_ap_start = start_for_Loop_Loop2_proc_U0_empty_n;

assign Loop_Loop3_proc_U0_ap_continue = ap_sync_done;

assign Loop_Loop3_proc_U0_ap_start = start_for_Loop_Loop3_proc_U0_empty_n;

assign ap_done = ap_sync_done;

assign ap_idle = (split_U0_ap_idle & Loop_Loop3_proc_U0_ap_idle & Loop_Loop2_proc_U0_ap_idle & Loop_Loop1_proc_U0_ap_idle);

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign ap_ready = Loop_Loop1_proc_U0_ap_ready;

assign ap_sync_done = (Loop_Loop3_proc_U0_ap_done & Loop_Loop2_proc_U0_ap_done);

assign data_in_address0 = Loop_Loop1_proc_U0_data_in_address0;

assign data_in_address1 = 14'd0;

assign data_in_ce0 = Loop_Loop1_proc_U0_data_in_ce0;

assign data_in_ce1 = 1'b0;

assign data_in_d0 = 32'd0;

assign data_in_d1 = 32'd0;

assign data_in_we0 = 1'b0;

assign data_in_we1 = 1'b0;

assign data_out1_address0 = Loop_Loop2_proc_U0_data_out1_address0;

assign data_out1_address1 = 14'd0;

assign data_out1_ce0 = Loop_Loop2_proc_U0_data_out1_ce0;

assign data_out1_ce1 = 1'b0;

assign data_out1_d0 = Loop_Loop2_proc_U0_data_out1_d0;

assign data_out1_d1 = 32'd0;

assign data_out1_we0 = Loop_Loop2_proc_U0_data_out1_we0;

assign data_out1_we1 = 1'b0;

assign data_out2_address0 = Loop_Loop3_proc_U0_data_out2_address0;

assign data_out2_address1 = 14'd0;

assign data_out2_ce0 = Loop_Loop3_proc_U0_data_out2_ce0;

assign data_out2_ce1 = 1'b0;

assign data_out2_d0 = Loop_Loop3_proc_U0_data_out2_d0;

assign data_out2_d1 = 32'd0;

assign data_out2_we0 = Loop_Loop3_proc_U0_data_out2_we0;

assign data_out2_we1 = 1'b0;

assign split_U0_ap_continue = 1'b1;

assign split_U0_ap_start = start_for_split_U0_empty_n;

assign split_U0_start_full_n = (start_for_Loop_Loop3_proc_U0_full_n & start_for_Loop_Loop2_proc_U0_full_n);

assign start_for_Loop_Loop2_proc_U0_din = 1'b1;

assign start_for_Loop_Loop3_proc_U0_din = 1'b1;

assign start_for_split_U0_din = 1'b1;

endmodule //foo_m
